[[redirects]]
  from = "/src/assets/CV_VanessaOliveros.pdf"
  to = "/src/assets/CV_VanessaOliveros.pdf"
  status = 200

[[headers]]
  for = "/src/assets/CV_VanessaOliveros.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment; CV_VanessaOliveros.pdf"
    Cache-Control = "public, max-age=0"
